micronaut:
  application:
    name: server
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - "http://localhost:8090"
            - "http://client:80"
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
